name: Publish NPM Version Info (disabled for derivative repository)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dispatch:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: SoulBoy-TjT/lx-music-desktop-plus-version-info
          event-type: npm-release
